In [32]:
import os
import collections
import math
import pandas as pd
import numpy as np
from IPython.display import display
baseDir = os.getcwd()
file = os.path.join(baseDir, 'input.txt')
# print(file)
if (os.path.isfile(file)):
    with open(file, "r") as dataFile:
        listData = [ inputData.rstrip("\n").split(" ") for inputData in dataFile.readlines() ]
n = int(listData[0][0])
print(n)

from datetime import timedelta
from datetime import datetime
start_date = datetime.strptime('2020-04-11', '%Y-%m-%d')
finish_date = datetime.strptime('2020/28/10_@_11/05/30', '%Y-%d-%m_@_%H:%M:%S')
date = []
info = []
for i in range(1, len(listData)): 
    date.append(pd.to_datetime(datetime.strptime(listData[i][0], '%Y-%m-%d_%H:%M:%S')))
    info.append([listData[i][1], listData[i][2], listData[i][3]])
index = pd.DatetimeIndex(date)
index.name = 'date'
df_info = pd.DataFrame(info, index=index, columns=columns)
idx = pd.IndexSlice

6


In [33]:
baseDir = 'C:\\Users\\MKoga\\MyProgramms\\BusinessAnalysis\\Yandex_cup\\'
file1 = os.path.join(baseDir, 'qid_url_rating.tsv')
file2 = os.path.join(baseDir, 'hostid_url.tsv')
file3 = os.path.join(baseDir, 'qid_query.tsv')
requestToText = pd.read_table(file3, names=['request id', 'text'])
hostToUrl = pd.read_table(file2, names=['host id', 'url'])
allData = pd.read_table(file1, names=['request id', 'url', 'rel'])

In [ ]:
    listNotUseShops = ['JU', 'PZ', 'AT', 'WA', 'CA', 'NB']
    
    sql = "SELECT * FROM ОстаткиПродажиМагазинов Where"
    useShops = '(Магазин not in ('
    useShops += ', '.join(["'" + shop + "'" for shop in listNotUseShops])
    useShops += ') '
    useGoods = 'AND (Товар in ('
    useGoods += ', '.join(["'" + article + "'" for article in listGoods])
    sql += useShops
    sql += useGoods
    sql += ') AND Дата BETWEEN ? AND ?)'
    
    for weekNumber in range(1, 105, 1):
        print('week number - %d' %weekNumber)
        startDate = str((finishDate - weekNumber * Week()).to_period('D'))
        #print(startDate)
        endDate = str((finishDate - (weekNumber - 1) * Week()).to_period('D'))
        #print(endDate)

        cur.execute(sql, (startDate, endDate))

In [1]:
def nFactorial(n):
    if n > 0:
        return n * nFactorial(n-1)
    else:
        return 1

In [2]:
def nAk(n, k):
    if k > 0:
        return n * nAk(n-1, k-1)
    else:
        return 1

In [3]:
def nCk(n, k, nAk, nFactorial):
    return nAk(n, k) / nFactorial(k)

In [22]:
def NOD(a, b):
    while True:
        if a < b:
            a, b = b, a   
        a %= b
        if a == 0:
            return b    

In [5]:
def skew_product_vectors(A, B): # A(x1, y1) B(x2, y2)
    return  A[0] * B[1] - A[1] * B[0] 

In [6]:
def skew_product_ABxAC(A, B, C): # A(x1, y1) B(x2, y2) C(x3, y3)
    AB = (B[0] - A[0], B[1] - A[1])
    AC = (C[0] - A[0], C[1] - A[1])
    return  AB[0] * AC[1] - AB[1] * AC[0] 

In [8]:
def scalar_product_vectors(A, B): # A(x1, y1) B(x2, y2)
    return A[0] * B[0] + A[1] * B[1]

In [ ]:
def scalar_product_ABdotAC(A, B, c): # A(x1, y1) B(x2, y2) C(x3, y3)
    AB = (B[0] - A[0], B[1] - A[1])
    AC = (C[0] - A[0], C[1] - A[1])
    return AB[0] * AC[0] + AB[1] * AC[1]

In [ ]:
def printList(dataList):
    for x in dataList:
        print(x, end = ' ')

In [62]:
def splitLineBySectionMinMax(nPoints):
    data = nPoints[:, 1] # point is (x, y) np.array
    listIndexExtremePoints = []
    type_extreme_point = 0
    firstExtremePointFind = False
    for i in range(2, len(data) - 1):
        if not firstExtremePointFind or (firstExtremePointFind and need_type_extreme_point == 'min'):
            if data[i-2] > data[i-1] and data[i-1] > data[i] and (data[i+1] > data[i] or data[i+1] == 0):
                listIndexExtremePoints.append(i if firstExtremePointFind else 0)
                if not firstExtremePointFind:
                    need_type_extreme_point = 'max'
                firstExtremePointFind = True
        if not firstExtremePointFind or (firstExtremePointFind and need_type_extreme_point == 'max'):
            if data[i-2] < data[i-1] and data[i-1] < data[i] and data[i+1] < data[i]:
                listIndexExtremePoints.append(i if firstExtremePointFind else 0)
                if not firstExtremePointFind:
                    need_type_extreme_point = 'min'
                firstExtremePointFind = True
    if listIndexExtremePoints[-1] < len(data) - 4:
        listIndexExtremePoints.append(len(data) - 1)
    else:
        listIndexExtremePoints[-1] = len(data) - 1
    return listIndexExtremePoints

def PWL_func_on_get_Section(nPoints, list_border_section): # piecewiseLinear(PWL)
    nInterval = len(list_border_section) - 1
    for i in range(nInterval):
        fp = np.polyfit(nPoints[list_border_section[i] : list_border_section[i+1], 0], 
                        nPoints[list_border_section[i] : list_border_section[i+1], 1], 1) 
        print(fp)

In [63]:
import os
import collections
import math
import pandas as pd
import numpy as np
import numpy.matlib

x = np.arange(0, 2, 0.1)
y = 2 * x
y_add = 1 * np.random.randn(20) + 1
y = y + y_add
nPoint = np.array([(i, j) for i, j in zip(x, y)])
print(nPoint)
listExtreme = splitLineBySectionMinMax(nPoint)
print(listExtreme)
PWL_func_on_get_Section(nPoint, listExtreme)

[[0.         1.24244303]
 [0.1        1.49951558]
 [0.2        1.51438716]
 [0.3        0.51138177]
 [0.4        1.16447243]
 [0.5        3.38778727]
 [0.6        2.78550025]
 [0.7        1.18477403]
 [0.8        2.0111008 ]
 [0.9        2.51148074]
 [1.         3.72619467]
 [1.1        3.45706361]
 [1.2        3.4818512 ]
 [1.3        5.21612198]
 [1.4        4.17273209]
 [1.5        4.56029524]
 [1.6        4.87352792]
 [1.7        3.98693636]
 [1.8        4.73654234]
 [1.9        4.43499069]]
[0, 7, 19]
[2.87707154 0.86623389]
[2.84748534 0.10052841]


In [66]:
import numpy as np
X = np.arange(16).reshape((4, 4))
print(X)
# выбор строк из 2-х мерного массива numpy
row = np.array([1, 3])
col = np.array([i for i in range(X.shape[1])])
print(X[row[:,np.newaxis], col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [12 13 14 15]]
